name: Deploy Fragrance Guess App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: fragrance-app-rg
          template: ./infra/main.bicep
          parameters: location=eastus
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies and Create Zip Package
        run: |
          cd app
          pip install --target=".python_packages/lib/site-packages" -r requirements.txt
          zip -r ../deploy.zip . *

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: fragrance-guess-app
          package: deploy.zip
