name: Deploy Sensory Evaluation Quiz

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Azure CLI 2.72.0
        run: |
          az version
          sudo apt-get install azure-cli=2.72.0* -y --allow-downgrades
          az version
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Bicep Template
        id: deploy_bicep
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: sensory-rg
          resourceGroupLocation: centralus
          template: ./infra/main.bicep
          parameters: location=centralus
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies and Create Zip Package
        run: |
          cd app
          pip install --target=".python_packages/lib/site-packages" -r requirements.txt
          zip -r ../deploy.zip . *

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ steps.deploy_bicep.outputs.webAppName }}
          package: deploy.zip
